### ISSUE TITLE
Small memory leak issue

### ISSUE THREAD

**Issue by astrochun** [toggl-open-source/toggldesktop#3813]
### 💻 Environment
Platform: macOS
OS Version: 10.14.6
Toggl Version: 7.5.42

### 🐞 Actual behavior
A follow-up on #3766: Further monitoring of memory use indicate a small memory leak.  Upon opening the Toggl application, the memory use is at ~60MB.  Over time, it has been seen to rise gradually. Most recently, it's been seen at 280MB after the application has been opened for over 5 days. Others have reported memory usage of ~100MB at most.  Certainly the patch in 7.5.42 fixed the high memory leak, but perhaps there is a secondary leak.  For comparison, the memory usage level is comparable to Google Chrome.

### 💯 Expected behavior
Lower memory usage

### 🔨 Steps to reproduce

1. Start Toggl on macOS 10.14.6
2. Monitor memory usage with time

### 📦 Additional info
This does not appear to affect older Mac (e.g., Mac OSX 10.11.6)

Here's a screenshot of memory usage:
<img width="451" alt="Screen Shot 2020-02-16 at 9 58 11 AM" src="https://user-images.githubusercontent.com/20305734/74609029-46722b00-50a3-11ea-81e7-af982993803f.png">

**Comment by NghiaTranUIT** [comment]
Thank for the report. We also notice that there are still some small memory leaking too. Our team will keep investigating and completely fix it soon 👍

**Comment by astrochun** [comment]
I noticed that 7.5.49 is released but the changelog does not mention any memory leak issue fix.  Could an update be provided? Thanks.

**Comment by NghiaTranUIT** [comment]
Sorry for that but the build 7.5.49 mainly focus on the Timeline v2 and we haven't investigated the memory leak further.

**Comment by toszcze** [comment]
The memory usage after 6 hours. Version 7.5.85 on macOS 10.14.6. Please let me know if you need more details.

<img width="450" alt="" src="https://user-images.githubusercontent.com/373659/78710960-7fe24c80-7916-11ea-8926-0cf8edc0a138.png">

**Comment by toszcze** [comment]
@NghiaTranUIT Has this fix been released yet? I'm using 7.5.113 and after few hours the memory usage went up to 1.82 GB. :/

**Comment by skel35** [comment]
@toszcze Memory leak fixes were done right after 7.5.113. Please try the latest beta, version 7.5.115, and let us know if you still experience high memory usage.

**Comment by toszcze** [comment]
@skel35 Thanks! I just installed 7.5.115, let's see if it fixes the issue. Thanks for your hard work! 👍

**Comment by toszcze** [comment]
@skel35 Unfortunately the issue still exists. :/ I'm using 7.5.115, after ~12 hours the RAM usage went up to 1.88 GB.
<img width="446" alt="Zrzut ekranu 2020-04-24 15 01 54" src="https://user-images.githubusercontent.com/373659/80215451-c1743680-863c-11ea-82eb-99a9a975a464.png">

**Comment by NghiaTranUIT** [comment]
Thank you for reporting @toszcze

Even though we fixed a bunch of leaking in our HTTPClient, but we believe that there is some leak in the Timeline feature when it records the Timeline Events

Reopen the ticket and I will investigate further 👍

**Comment by astrochun** [comment]
Same here after about 12-hr of use with 7.5.115.  Is there a way to disable/turn off Timeline? I don't use this feature generally.

**Comment by NghiaTranUIT** [comment]
Yes, you can turn off the Record Activity switch to avoid memory leak (see screenshot)

If you still encounter the memory leak, please report us 👍 

![Preview-Timeline-v2](https://user-images.githubusercontent.com/5878421/80217904-a1f40280-866a-11ea-89e1-fe52a1118d6b.png)

**Comment by astrochun** [comment]
I actually have that "Record Activity" turn off.
<img width="317" alt="Screen Shot 2020-04-24 at 6 36 23 AM" src="https://user-images.githubusercontent.com/20305734/80218396-fad58380-85f5-11ea-86b5-a28a52ba981d.png">

**Comment by toszcze** [comment]
I also have the Record Activity turned off.

**Comment by VitaliyHTC** [comment]
Also have same issue (Record activity off). After restart it use much less memory. My colegue have this issue with 2.96GB of memory use.
<img width="765" alt="Screen Shot 2020-04-25 at 13 25 19" src="https://user-images.githubusercontent.com/1236249/80277756-e9759f80-86f9-11ea-9879-8b8ed2e31e81.png">
<img width="763" alt="Screen Shot 2020-04-25 at 13 26 39" src="https://user-images.githubusercontent.com/1236249/80277760-ee3a5380-86f9-11ea-9498-a445f9c32877.png">

**Comment by kapooostin** [comment]
I like the Record Activity, but not long ago Toggl began to end up with 12–14 GB of RAM to itself after a day of usage.
toggl v. 7.5.119
macOS 10.14.6

**Comment by NghiaTranUIT** [comment]
@here The memory leaking is finally fixed in the stable 7.5.123

Please download it and let us know the update 👍 Thank you guys in advance 🌮

**Comment by sonthomsen** [comment]
I still have the issue in Mojave 10.14.6 and Toggle Desktop 7.5.123 with Record Activity set to off
