### ISSUE TITLE
Expired Root Certificate for desktop.toggl.com

### ISSUE THREAD

**Issue by tomrit** [toggl-open-source/toggldesktop#4119]
Unable to sync via TogglDesktop since today. This seems to be caused by the end of validity of the certificates used by desktop.toggl.com (AddTrust External CA Root Sat, 30 May 2020 10:48:38 UT).

**Comment by sahiljuneja** [comment]
I have been unable to sync as well. Possibly facing login issues on the Windows Desktop App because of the same.

**Comment by cameronj86** [comment]
Same

**Comment by matinas** [comment]
Same here

**Comment by tomrit** [comment]
Seems to stem from this certificate sent by the server  desktop.toggl.com:

Common name: COMODO RSA Certification Authority
Organization: COMODO CA Limited
Location: Salford, Greater Manchester, GB
Valid from May 30, 2000 to **_May 30, 2020_**
Serial Number: 2766ee56eb49f38eabd770a2fc84de22
Signature Algorithm: sha384WithRSAEncryption
Issuer: AddTrust External CA Root

**Comment by tomrit** [comment]
just solved by @skel35, thanks!

**Comment by matinas** [comment]
I'm still having the issue. Can't log in, I get an error message "Login failed. Are you online?"

Is it working for everyone else?

**Comment by skel35** [comment]
The patched app fixes the issue.
Please download a new version of the app
64-bit: https://toggl.github.io/toggldesktop/download/windows64-stable/
32-bit: https://toggl.github.io/toggldesktop/download/windows-stable/

Most of the users can auto-update from About view or by restarting the app.
