### ISSUE TITLE
When continuing a time entry the wrong description applies

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#4405]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.13 
Toggl Version: 7.4.260

### 💯 Expected behavior

The following video shows the issue: [video link 🔗](https://drive.google.com/file/d/12Md6d8LJOHjuJjC7tAQ43JJUd_L8RY3Z/view?usp=drivesdk) 

### 🔨 Steps to reproduce

1. Start a running timer
2. Continue tracking based on another time entry in the list by clicking the play button next to it
3. Change to another time entry by clicking the play button next to another existing one and observe the description

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481303546566)

[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481301378326)

**Comment by skel35** [comment]
already fixed in beta, will soon be fixed in stable

**Comment by VeljkoTN** [comment]
@skel35 user 2822187 says this is still happening for them even with the beta

**Comment by skel35** [comment]
this user is still on 7.5.260 based on Backoffice.
the bug is fixed in the latest stable already, which is 7.5.268.

**Comment by VeljkoTN** [comment]
Hm good catch, I'll ask them to confirm.
